# Generated by Django 5.2.3 on 2025-06-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_users_email_users_first_name_users_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
        ),
    ]
