# Generated by Django 5.2.3 on 2025-06-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_wishlist_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('bannerid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/media/')),
            ],
        ),
    ]
