# Generated by Django 5.2.3 on 2025-06-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_banner_image_alter_banner_title_cart_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('phonenumber', models.CharField(max_length=10)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
